# Generated by Django 6.1 on 2026-08-14 03:11

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("client", models.GenericIPAddressField()),
                ("qname", models.CharField(max_length=253)),
                ("qtype", models.CharField(max_length=16)),
                ("rcode", models.CharField(blank=True, max_length=16)),
                ("reply_ms", models.FloatField(blank=True, null=True)),
                ("blocked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "queries",
                "ordering": ["-at"],
                "indexes": [
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["at"], name="queries_query_at_brin"
                    ),
                    models.Index(fields=["qname"], name="queries_query_qname"),
                    models.Index(fields=["client"], name="queries_query_client"),
                ],
            },
        ),
    ]
