# Generated by Django 6.1 on 2026-08-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("client", models.GenericIPAddressField()),
                ("blocked", models.BooleanField()),
                ("count", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("at", "client", "blocked"),
                        name="one_row_per_client_per_hour",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Top",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateField()),
                ("qname", models.CharField(max_length=253)),
                ("blocked", models.BooleanField()),
                ("count", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-at", "-count"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("at", "qname", "blocked"),
                        name="one_row_per_name_per_day",
                    )
                ],
            },
        ),
    ]
