# Generated by Django 6.1 on 2026-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("block", "Block, answer NXDOMAIN"),
                            ("block_nodata", "Block, answer NODATA"),
                            ("allow", "Allow, skip the blocklist"),
                        ],
                        default="block",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added by hand"),
                            ("query_log", "Added from the query log"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="rules_rule_expires_f910dc_idx"
                    )
                ],
            },
        ),
    ]
