# Generated by Django 6.1 on 2026-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0002_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="serial",
            field=models.BigIntegerField(default=1),
        ),
    ]
